import { Link } from '@tanstack/react-router'
import { ArrowRight, Award, BarChart3, BookOpenCheck, Clock3, Flame, Play, Sparkles, Target, Trophy, Zap } from 'lucide-react'
import { challenges } from '@/data/challenges'
import { skillProgress } from '@/data/skills'
import { useArena } from '@/components/app-provider'
import { Badge, Button, DifficultyBadge, ListArrow, Panel, ProgressBar, StatCard } from '@/components/ui'
import { categoryLabels, skillLabels, statusLabels } from '@/lib/i18n'
import { levelFromXp, xpForNextLevel } from '@/lib/scoring/xp'

export function Dashboard() {
  const { progress, sessions, settings } = useArena()
  const level = levelFromXp(progress.totalXp)
  const nextLevel = xpForNextLevel(level)
  const currentLevelXp = xpForNextLevel(level - 1)
  const xpProgress = Math.round(((progress.totalXp - currentLevelXp) / (nextLevel - currentLevelXp)) * 100)
  const activeSession = sessions.find((session) => session.challengeId && !session.completedAt)
  const activeChallenge = activeSession ? challenges.find((challenge) => challenge.id === activeSession.challengeId) : undefined
  const recommendedChallenge = settings.trainingFocus === 'WorldSkills' ? challenges.find((challenge) => challenge.difficulty === 'WorldSkills') ?? challenges[0] : challenges.find((challenge) => challenge.category === settings.trainingFocus) ?? challenges[0]
  const ratedSkills = skillProgress.filter((skill) => (progress.skillProgress[skill.name] ?? 0) > 0)
  const weakest = [...ratedSkills].sort((a, b) => (progress.skillProgress[a.name] ?? 0) - (progress.skillProgress[b.name] ?? 0)).slice(0, 3)
  const scoredValues = Object.values(progress.scores)
  const averageScore = scoredValues.length ? `${Math.round(scoredValues.reduce((sum, score) => sum + score, 0) / scoredValues.length)} %` : '—'
  const averageCaption = scoredValues.length ? `${scoredValues.length} score${scoredValues.length > 1 ? 's' : ''} enregistré${scoredValues.length > 1 ? 's' : ''}` : 'Aucun score enregistré'
  const today = new Intl.DateTimeFormat('fr-FR', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }).format(new Date())
  const hour = new Date().getHours()
  const greeting = hour < 12 ? 'Bonjour' : hour < 18 ? 'Bon après-midi' : 'Bonsoir'

  return <div className="panel-in space-y-6">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 text-[10px] font-semibold uppercase tracking-[.2em] text-[#5b8fc8]">{today}</p><h1 className="text-[26px] font-semibold tracking-[-.05em] text-[#f2f6fc] sm:text-[30px]">{settings.displayName ? `${greeting}, ${settings.displayName}` : 'Bienvenue dans CodeArena'}</h1><p className="mt-1.5 text-[12px] text-[#8ca6c2]">Chaque challenge terminé alimente ton niveau et ton historique réel.</p></div><Link to="/practice"><Button><Play size={14} fill="currentColor" /> Démarrer une session</Button></Link></div>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><StatCard label="Niveau" value={String(level)} caption={`${progress.totalXp.toLocaleString('fr-FR')} XP au total`} icon={Zap} color="#4da3ff" progress={xpProgress} /><StatCard label="Challenges" value={String(progress.completedChallenges.length).padStart(2, '0')} caption={progress.completedChallenges.length ? 'terminés' : 'Aucun terminé'} icon={Trophy} color="#a58bff" /><StatCard label="Temps d’entraînement" value={progress.totalTrainingMinutes ? `${Math.floor(progress.totalTrainingMinutes / 60)} h ${progress.totalTrainingMinutes % 60} min` : '—'} caption={progress.totalTrainingMinutes ? 'temps cumulé' : 'Aucune session'} icon={Clock3} color="#4da3ff" /><StatCard label="Série actuelle" value={progress.streak ? `${progress.streak} jour${progress.streak > 1 ? 's' : ''}` : '—'} caption={progress.streak ? `Record : ${progress.bestStreak} jours` : 'Aucune série en cours'} icon={Flame} color="#ef8845" pulse={progress.streak > 0} /><StatCard label="Score moyen" value={averageScore} caption={averageCaption} icon={Award} color="#f4c84e" /></div>
    <div className="grid gap-4 xl:grid-cols-[1.35fr_.85fr]">
      <Panel className="overflow-hidden"><div className="flex items-center justify-between border-b thin-rule px-4 py-3"><div><p className="text-[11px] font-semibold text-[#e9f2fc]">{activeChallenge ? 'Reprendre ta session' : 'Prochaine étape'}</p><p className="mt-0.5 text-[10px] text-[#7894b0]">{activeChallenge ? 'Une session est en cours dans ton espace local.' : 'Aucune session en cours : choisis un premier bloc.'}</p></div><Badge tone={activeChallenge ? 'green' : 'blue'}><Sparkles size={11} /> {activeChallenge ? 'En cours' : 'Recommandé'}</Badge></div><div className="grid gap-5 p-4 md:grid-cols-[1fr_230px] md:items-center"><div><div className="flex items-center gap-2"><Badge tone="blue">{categoryLabels[(activeChallenge ?? recommendedChallenge).category]}</Badge><DifficultyBadge difficulty={(activeChallenge ?? recommendedChallenge).difficulty} /></div><h2 className="mt-3 text-[20px] font-semibold tracking-[-.04em] text-white">{(activeChallenge ?? recommendedChallenge).title}</h2><p className="mt-2 max-w-[52ch] text-[12px] leading-5 text-[#91a9c2]">{(activeChallenge ?? recommendedChallenge).description}</p>{activeChallenge ? <p className="mt-4 text-[10px] text-[#83a1be]">Session démarrée · le temps réel sera enregistré à la fin.</p> : null}<Link to="/challenges/$challengeId" params={{ challengeId: (activeChallenge ?? recommendedChallenge).id }} className="mt-4 inline-flex"><Button>{activeChallenge ? 'Reprendre le challenge' : 'Voir le challenge'} <ArrowRight size={14} /></Button></Link></div><div className="relative hidden h-[150px] overflow-hidden rounded-[8px] border border-[#2c5781] bg-[#102c4e] md:block"><div className="absolute -right-7 -top-8 h-32 w-32 rounded-full border-[16px] border-[#1d5ba2] opacity-50" /><div className="absolute bottom-6 left-7 h-16 w-24 rotate-[-8deg] border border-[#5499e9] bg-[#1c5796]/70" /><div className="absolute left-1/2 top-1/2 grid h-12 w-12 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full bg-[#3e91f1] text-white shadow-[0_8px_26px_rgba(49,139,237,.4)]"><Play size={20} fill="currentColor" /></div><p className="absolute bottom-3 left-3 text-[9px] uppercase tracking-[.2em] text-[#8cb9ed]">{categoryLabels[(activeChallenge ?? recommendedChallenge).category]}</p></div></div></Panel>
      <Panel className="overflow-hidden"><div className="flex items-center justify-between border-b thin-rule px-4 py-3"><div><p className="text-[11px] font-semibold text-[#e9f2fc]">Pour commencer</p><p className="mt-0.5 text-[10px] text-[#7894b0]">Une recommandation basée sur ton axe de départ.</p></div><Target size={16} className="text-[#5ea2ff]" /></div><div className="p-4"><div className="flex items-center gap-2"><Badge tone="purple">{categoryLabels[recommendedChallenge.category]}</Badge><DifficultyBadge difficulty={recommendedChallenge.difficulty} /></div><h2 className="mt-3 text-[18px] font-semibold tracking-[-.035em] text-white">{recommendedChallenge.title}</h2><p className="mt-2 text-[12px] leading-5 text-[#91a9c2]">{recommendedChallenge.description}</p><div className="mt-5 flex items-center gap-4 text-[10px] text-[#809bb7]"><span className="inline-flex items-center gap-1"><Clock3 size={12} /> {recommendedChallenge.estimatedMinutes} min</span><span className="inline-flex items-center gap-1 text-[#f4cc52]"><Zap size={12} /> {recommendedChallenge.xp} XP</span></div><Link to="/challenges/$challengeId" params={{ challengeId: recommendedChallenge.id }} className="mt-5 inline-flex w-full"><Button className="w-full">Ouvrir le challenge <ArrowRight size={14} /></Button></Link></div></Panel>
    </div>
    <div className="grid gap-4 lg:grid-cols-[1fr_1fr_.78fr]"><Panel title="Ta progression par compétence" action={<Link to="/progress" className="text-[10px] font-medium text-[#6daeff] hover:text-white">Voir le détail</Link>}><div className="space-y-4 p-4">{skillProgress.slice(0, 5).map((skill) => { const score = progress.skillProgress[skill.name] ?? 0; return <div key={skill.name}><div className="mb-1.5 flex items-center justify-between text-[11px]"><span className="text-[#b5c9dd]">{skillLabels[skill.name] ?? skill.name}</span><span className="font-mono text-[10px] text-[#8aa5c1]">{score > 0 ? `${score} %` : '—'}</span></div><ProgressBar value={score} color={skill.color} /></div> })}</div></Panel><Panel title="Compétences à renforcer" action={<Link to="/practice" className="text-[10px] font-medium text-[#6daeff] hover:text-white">Pratiquer</Link>}>{weakest.length ? <div className="divide-y divide-[#203d5a]">{weakest.map((skill) => <div key={skill.name} className="flex items-center gap-3 px-4 py-3"><span className="grid h-7 w-7 place-items-center rounded-[6px]" style={{ backgroundColor: `${skill.color}1c`, color: skill.color }}><BarChart3 size={14} /></span><div className="min-w-0 flex-1"><p className="truncate text-[11px] font-medium text-[#dbe8f7]">{skillLabels[skill.name] ?? skill.name}</p><p className="mt-0.5 text-[10px] text-[#718ca8]">Une compétence à retravailler.</p></div><Link to="/practice" className="rounded-[5px] border border-[#315679] px-2 py-1 text-[10px] text-[#7fb5ed] hover:bg-[#183753]">Pratiquer</Link></div>)}</div> : <div className="p-5"><p className="text-[11px] font-medium text-[#dbe8f7]">Aucune compétence évaluée</p><p className="mt-1 text-[10px] leading-4 text-[#718ca8]">Termine un challenge pour commencer à voir tes points forts et tes axes de travail.</p></div>}</Panel><Panel className="relative min-h-[204px] overflow-hidden bg-[linear-gradient(145deg,#182b43,#0c1726)]"><div className="absolute inset-0 opacity-50" style={{ backgroundImage: 'radial-gradient(circle at 75% 20%, rgba(69,145,226,.3), transparent 38%), linear-gradient(125deg, transparent 20%, rgba(99,154,211,.08) 20.5%, transparent 21%)' }} /><div className="relative flex h-full flex-col justify-end p-4"><BookOpenCheck size={20} className="mb-auto text-[#7db8f6]" /><p className="max-w-[18ch] text-[17px] font-semibold leading-5 tracking-[-.03em] text-white">Même pratique. Exigences supérieures.</p><p className="mt-2 text-[10px] leading-4 text-[#8ca8c3]">Chaque résultat est enregistré localement, sans profil de démonstration.</p></div></Panel></div>
    <Panel title="Sessions récentes" action={<Link to="/progress" className="text-[10px] font-medium text-[#6daeff] hover:text-white">Voir l’historique</Link>}>{sessions.length ? <div className="grid divide-y divide-[#203d5a] sm:grid-cols-3 sm:divide-x sm:divide-y-0">{sessions.slice(0, 3).map((session) => { const challenge = session.challengeId ? challenges.find((item) => item.id === session.challengeId) : undefined; const status = session.completedAt ? 'completed' : 'in-progress'; return <div className="flex items-center gap-3 px-4 py-3" key={session.id}><div className="grid h-8 w-8 place-items-center rounded-[6px] bg-[#153250] text-[#65adff]"><BookOpenCheck size={15} /></div><div className="min-w-0 flex-1"><p className="truncate text-[11px] font-medium text-[#dce9f7]">{challenge?.title ?? 'Session'}</p><p className="mt-0.5 text-[10px] text-[#7894af]">{statusLabels[status]} · {session.duration} min</p></div><span className="font-mono text-[11px] text-[#9ab4cf]">{session.score !== undefined ? `${session.score} %` : 'En cours'}</span><ListArrow /></div> })}</div> : <div className="flex flex-wrap items-center justify-between gap-3 p-5"><div><p className="text-[11px] font-medium text-[#dce9f7]">Aucune session enregistrée</p><p className="mt-1 text-[10px] text-[#7894af]">Ton historique apparaîtra ici après ton premier challenge.</p></div><Link to="/practice"><Button variant="secondary">Commencer à pratiquer <ArrowRight size={13} /></Button></Link></div>}</Panel>
  </div>
}
