import { ExternalLink, FileText, FolderOpen, GitBranch, Globe2, Library, Plus, Search, Star } from 'lucide-react'
import { Badge, Button, Panel } from '@/components/ui'

const resources = [
  { title: 'Documentation React', type: 'React', description: 'La référence officielle des composants, hooks et API.', href: 'https://react.dev', icon: Library, color: '#4da3ff' },
  { title: 'Guide JavaScript MDN', type: 'JavaScript', description: 'Une référence durable pour le langage et les API du navigateur.', href: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript', icon: FileText, color: '#f4c84e' },
  { title: 'Référence HTML MDN', type: 'HTML', description: 'Éléments, sémantique, formulaires et structure accessible.', href: 'https://developer.mozilla.org/en-US/docs/Web/HTML', icon: Globe2, color: '#f06b4a' },
  { title: 'CSS Tricks Almanac', type: 'CSS', description: 'Des patterns pratiques pour la mise en page, Grid et le responsive.', href: 'https://css-tricks.com/almanac/', icon: FolderOpen, color: '#42a5f5' },
  { title: 'Accessibilité Web.dev', type: 'Accessibilité', description: 'Audits, patterns et habitudes de test pour des interfaces inclusives.', href: 'https://web.dev/learn/accessibility', icon: Star, color: '#a28bff' },
  { title: 'Manuel Git', type: 'Git', description: 'Une référence courte pour les commandes de versioning utiles.', href: 'https://guides.github.com/introduction/git-handbook/', icon: GitBranch, color: '#2fc4a6' },
]

export function ResourcesView() {
  return <div className="panel-in space-y-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="mb-2 text-[10px] font-semibold uppercase tracking-[.2em] text-[#5b8fc8]">Ressources / bibliothèque personnelle</p><h1 className="text-[26px] font-semibold tracking-[-.05em] text-white">Garde la bonne référence à portée de main.</h1><p className="mt-1.5 text-[12px] text-[#8ca6c2]">Une petite sélection fiable pour les moments où une notion mérite un second regard.</p></div><Button variant="secondary"><Plus size={14} /> Ajouter une ressource</Button></div><div className="surface-panel-flat flex items-center gap-3 rounded-[9px] p-3"><Search size={15} className="text-[#6383a3]" /><input className="focus-ring h-8 flex-1 bg-transparent text-[11px] text-white outline-none placeholder:text-[#6784a0]" placeholder="Rechercher dans ta bibliothèque…" aria-label="Rechercher des ressources" /><Badge tone="slate">6 liens</Badge></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{resources.map(({ title, type, description, href, icon: Icon, color }) => <a key={title} href={href} target="_blank" rel="noreferrer" className="group surface-panel-flat rounded-[9px] p-4 transition-all duration-200 hover:-translate-y-0.5 hover:border-[#3e6e9d]"><div className="flex items-start justify-between"><span className="grid h-9 w-9 place-items-center rounded-[7px]" style={{ color, backgroundColor: `${color}1b` }}><Icon size={17} /></span><ExternalLink size={14} className="text-[#5e7b99] transition-colors group-hover:text-[#84bcff]" /></div><div className="mt-5 flex items-center gap-2"><h2 className="text-[13px] font-semibold text-[#edf4fc]">{title}</h2><Badge tone="slate">{type}</Badge></div><p className="mt-2 text-[11px] leading-5 text-[#839db8]">{description}</p><p className="mt-4 border-t border-[#26445f] pt-3 text-[10px] text-[#6f8ba8]">Ouvrir la référence →</p></a>)}</div><Panel title="Tes notes" action={<Button variant="ghost" className="px-2 py-1 text-[10px]"><Plus size={12} /> Nouvelle note</Button>}><div className="p-5 text-center"><FileText size={21} className="mx-auto text-[#6286aa]" /><h2 className="mt-3 text-[13px] font-semibold text-[#dfeaf6]">Aucune note personnelle</h2><p className="mt-1 text-[11px] text-[#7c98b4]">Capture une explication courte pendant que la notion est encore fraîche.</p></div></Panel></div>
}
