/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as CompetitionRouteImport } from './routes/competition'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ChallengesChallengeIdRouteImport } from './routes/challenges_.$challengeId'
import { Route as PracticeReactRouteImport } from './routes/practice.react'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionRoute = CompetitionRouteImport.update({
  id: '/competition',
  path: '/competition',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesChallengeIdRoute = ChallengesChallengeIdRouteImport.update({
  id: '/challenges_/$challengeId',
  path: '/challenges/$challengeId',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeReactRoute = PracticeReactRouteImport.update({
  id: '/react',
  path: '/react',
  getParentRoute: () => PracticeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/challenges': typeof ChallengesRoute
  '/competition': typeof CompetitionRoute
  '/practice': typeof PracticeRouteWithChildren
  '/progress': typeof ProgressRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/challenges/$challengeId': typeof ChallengesChallengeIdRoute
  '/practice/react': typeof PracticeReactRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/challenges': typeof ChallengesRoute
  '/competition': typeof CompetitionRoute
  '/practice': typeof PracticeRouteWithChildren
  '/progress': typeof ProgressRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/challenges/$challengeId': typeof ChallengesChallengeIdRoute
  '/practice/react': typeof PracticeReactRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/challenges': typeof ChallengesRoute
  '/competition': typeof CompetitionRoute
  '/practice': typeof PracticeRouteWithChildren
  '/progress': typeof ProgressRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/challenges_/$challengeId': typeof ChallengesChallengeIdRoute
  '/practice/react': typeof PracticeReactRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/challenges'
    | '/competition'
    | '/practice'
    | '/progress'
    | '/resources'
    | '/settings'
    | '/challenges/$challengeId'
    | '/practice/react'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/challenges'
    | '/competition'
    | '/practice'
    | '/progress'
    | '/resources'
    | '/settings'
    | '/challenges/$challengeId'
    | '/practice/react'
  id:
    | '__root__'
    | '/'
    | '/challenges'
    | '/competition'
    | '/practice'
    | '/progress'
    | '/resources'
    | '/settings'
    | '/challenges_/$challengeId'
    | '/practice/react'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChallengesRoute: typeof ChallengesRoute
  CompetitionRoute: typeof CompetitionRoute
  PracticeRoute: typeof PracticeRouteWithChildren
  ProgressRoute: typeof ProgressRoute
  ResourcesRoute: typeof ResourcesRoute
  SettingsRoute: typeof SettingsRoute
  ChallengesChallengeIdRoute: typeof ChallengesChallengeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competition': {
      id: '/competition'
      path: '/competition'
      fullPath: '/competition'
      preLoaderRoute: typeof CompetitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges_/$challengeId': {
      id: '/challenges_/$challengeId'
      path: '/challenges/$challengeId'
      fullPath: '/challenges/$challengeId'
      preLoaderRoute: typeof ChallengesChallengeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/react': {
      id: '/practice/react'
      path: '/react'
      fullPath: '/practice/react'
      preLoaderRoute: typeof PracticeReactRouteImport
      parentRoute: typeof PracticeRoute
    }
  }
}

interface PracticeRouteChildren {
  PracticeReactRoute: typeof PracticeReactRoute
}

const PracticeRouteChildren: PracticeRouteChildren = {
  PracticeReactRoute: PracticeReactRoute,
}

const PracticeRouteWithChildren = PracticeRoute._addFileChildren(
  PracticeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChallengesRoute: ChallengesRoute,
  CompetitionRoute: CompetitionRoute,
  PracticeRoute: PracticeRouteWithChildren,
  ProgressRoute: ProgressRoute,
  ResourcesRoute: ResourcesRoute,
  SettingsRoute: SettingsRoute,
  ChallengesChallengeIdRoute: ChallengesChallengeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
